# Generated by Django 4.2.1 on 2023-05-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=255)),
                ('Donate_ddate', models.DateTimeField(auto_now=True)),
                ('phone', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('volume_donated', models.IntegerField(null=True)),
            ],
        ),
    ]
