# Generated by Django 4.2.1 on 2023-05-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='Donate_ddate',
            new_name='Donated_date',
        ),
    ]
